export const ROUTES = {
  LOGIN: "/login",
  SIGNUP: "/signup",
  VERIFY_EMAIL: "/verify-email",
  VERIFY_PHONE: "/verify-phone",
  DASHBOARD: "/dashboard",
  SOIL_TEST: "/soil-test",
  SOIL_ANALYZER: "/soil-analyzer",
  UPLOAD_REPORT: "/soil-test/upload",
  PROCESSING: "/soil-test/processing",
  VERIFY_DATA: "/soil-test/verify",
  REPORT: "/report",
  CROPS: "/recommendations/crops",
  FERTILIZER: "/recommendations/fertilizer",
  HISTORY: "/history",
  COMPARE: "/history/compare",
  ASSISTANT: "/assistant",
  PROFILE: "/profile",
  RESOURCES: "/government-resources",
  DEVELOPER_LOGIN: "/developer/login",
  DEVELOPER: "/developer",
  DEVELOPER_ADD_SCHEME: "/developer/scheme/add",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
} as const;
